### ISSUE TITLE
Multi-dimension dataset 

### ISSUE THREAD

**Issue by devna13** [pedrodbs/Aglomera#3]
I have a set with more than 2 features.. can this project can be expanded to work with more than 2 dimensions? 

Thanks

**Comment by pedrodbs** [comment]
This is already supported. 
Datapoints need only to implement the IComparable<T> interface, where the CompareTo method implements the distance function.

As per the example in the README file:
class DataPoint : IComparable<DataPoint>
{
    public DataPoint(string id, double x, double y) { ... }
    public int CompareTo(DataPoint other) { ... }
    ...
}

This has 2 dimensions/features, but you can implement datapoints with as many as you want.
